services:
  - type: web
    name: sanjeevni-backend
    rootDir: Backend
    env: docker
    plan: starter
    region: ohio
    envVars:
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: MURF_API_KEY
        sync: false
      - key: SWASYA_API_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"
      - key: NODEPATH
        value: node
